
// This file has been generated by the GUI designer. Do not modify.
namespace Mono.Upnp.Dcp.MediaServer1.FSpot
{
	public partial class SharingConfigDialog
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.Fixed fixed2;

		private global::Gtk.CheckButton lookForSharedLibrariesCheckbox;

		private global::Gtk.CheckButton shareMyLibraryCheckbox;

		private global::Gtk.RadioButton shareEntireLibraryRadioButton;

		private global::Gtk.RadioButton shareSelectedCategoriesRadioButton;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TreeView categoriesTreeView;

		private global::Gtk.Button buttonCancel;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Mono.Upnp.Dcp.MediaServer1.FSpot.SharingConfigDialog
			this.Name = "Mono.Upnp.Dcp.MediaServer1.FSpot.SharingConfigDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("UPnP Photo Sharing Preferences");
			this.Icon = global::Stetic.IconLoader.LoadIcon (this, "gtk-preferences", global::Gtk.IconSize.Menu);
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child Mono.Upnp.Dcp.MediaServer1.FSpot.SharingConfigDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.VscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w2 = new global::Gtk.Viewport ();
			w2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.fixed2 = new global::Gtk.Fixed ();
			this.fixed2.Name = "fixed2";
			this.fixed2.HasWindow = false;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.lookForSharedLibrariesCheckbox = new global::Gtk.CheckButton ();
			this.lookForSharedLibrariesCheckbox.CanFocus = true;
			this.lookForSharedLibrariesCheckbox.Name = "lookForSharedLibrariesCheckbox";
			this.lookForSharedLibrariesCheckbox.Label = global::Mono.Unix.Catalog.GetString ("Look for shared libraries");
			this.lookForSharedLibrariesCheckbox.DrawIndicator = true;
			this.lookForSharedLibrariesCheckbox.UseUnderline = true;
			this.fixed2.Add (this.lookForSharedLibrariesCheckbox);
			global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.lookForSharedLibrariesCheckbox]));
			w3.X = 13;
			w3.Y = 14;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.shareMyLibraryCheckbox = new global::Gtk.CheckButton ();
			this.shareMyLibraryCheckbox.CanFocus = true;
			this.shareMyLibraryCheckbox.Name = "shareMyLibraryCheckbox";
			this.shareMyLibraryCheckbox.Label = global::Mono.Unix.Catalog.GetString ("Share my library");
			this.shareMyLibraryCheckbox.DrawIndicator = true;
			this.shareMyLibraryCheckbox.UseUnderline = true;
			this.fixed2.Add (this.shareMyLibraryCheckbox);
			global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.shareMyLibraryCheckbox]));
			w4.X = 13;
			w4.Y = 43;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.shareEntireLibraryRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Share entire library"));
			this.shareEntireLibraryRadioButton.Sensitive = false;
			this.shareEntireLibraryRadioButton.CanFocus = true;
			this.shareEntireLibraryRadioButton.Name = "shareEntireLibraryRadioButton";
			this.shareEntireLibraryRadioButton.DrawIndicator = true;
			this.shareEntireLibraryRadioButton.UseUnderline = true;
			this.shareEntireLibraryRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.fixed2.Add (this.shareEntireLibraryRadioButton);
			global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.shareEntireLibraryRadioButton]));
			w5.X = 32;
			w5.Y = 71;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.shareSelectedCategoriesRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Share selected categories:"));
			this.shareSelectedCategoriesRadioButton.Sensitive = false;
			this.shareSelectedCategoriesRadioButton.CanFocus = true;
			this.shareSelectedCategoriesRadioButton.Name = "shareSelectedCategoriesRadioButton";
			this.shareSelectedCategoriesRadioButton.DrawIndicator = true;
			this.shareSelectedCategoriesRadioButton.UseUnderline = true;
			this.shareSelectedCategoriesRadioButton.Group = this.shareEntireLibraryRadioButton.Group;
			this.fixed2.Add (this.shareSelectedCategoriesRadioButton);
			global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.shareSelectedCategoriesRadioButton]));
			w6.X = 32;
			w6.Y = 97;
			// Container child fixed2.Gtk.Fixed+FixedChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.categoriesTreeView = new global::Gtk.TreeView ();
			this.categoriesTreeView.WidthRequest = 271;
			this.categoriesTreeView.HeightRequest = 240;
			this.categoriesTreeView.Sensitive = false;
			this.categoriesTreeView.CanFocus = true;
			this.categoriesTreeView.Name = "categoriesTreeView";
			this.categoriesTreeView.HeadersVisible = false;
			this.GtkScrolledWindow1.Add (this.categoriesTreeView);
			this.fixed2.Add (this.GtkScrolledWindow1);
			global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed2[this.GtkScrolledWindow1]));
			w8.X = 35;
			w8.Y = 124;
			w2.Add (this.fixed2);
			this.GtkScrolledWindow.Add (w2);
			w1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1[this.GtkScrolledWindow]));
			w11.Position = 0;
			// Internal child Mono.Upnp.Dcp.MediaServer1.FSpot.SharingConfigDialog.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonCancel]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-save";
			this.AddActionWidget (this.buttonOk, 0);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonOk]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 356;
			this.DefaultHeight = 429;
			this.Show ();
			this.shareMyLibraryCheckbox.Toggled += new global::System.EventHandler (this.OnShareMyLibraryCheckboxToggled);
			this.shareSelectedCategoriesRadioButton.Toggled += new global::System.EventHandler (this.OnShareSelectedCategoriesRadioButtonToggled);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
