// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.Upnp.GtkClient {
    
    
    public partial class ActionInvocationWindow {
        
        private Gtk.VBox vbox;
        
        private Gtk.Label action;
        
        private Gtk.Label label2;
        
        private Gtk.VBox inputsBox;
        
        private Gtk.Button button1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Mono.Upnp.GtkClient.ActionInvocationWindow
            this.WidthRequest = 0;
            this.HeightRequest = 0;
            this.Name = "Mono.Upnp.GtkClient.ActionInvocationWindow";
            this.Title = "Invoke Action";
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.DefaultWidth = 0;
            this.DefaultHeight = 0;
            // Container child Mono.Upnp.GtkClient.ActionInvocationWindow.Gtk.Container+ContainerChild
            this.vbox = new Gtk.VBox();
            this.vbox.Name = "vbox";
            this.vbox.Spacing = 6;
            this.vbox.BorderWidth = ((uint)(6));
            // Container child vbox.Gtk.Box+BoxChild
            this.action = new Gtk.Label();
            this.action.Name = "action";
            this.action.Xalign = 0F;
            this.action.LabelProp = "<big><b>action</b></big>";
            this.action.UseMarkup = true;
            this.vbox.Add(this.action);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox[this.action]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Input Arguments");
            this.vbox.Add(this.label2);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox[this.label2]));
            w2.Position = 1;
            w2.Expand = false;
            w2.Fill = false;
            // Container child vbox.Gtk.Box+BoxChild
            this.inputsBox = new Gtk.VBox();
            this.inputsBox.Name = "inputsBox";
            this.inputsBox.Spacing = 6;
            this.vbox.Add(this.inputsBox);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox[this.inputsBox]));
            w3.Position = 2;
            // Container child vbox.Gtk.Box+BoxChild
            this.button1 = new Gtk.Button();
            this.button1.CanFocus = true;
            this.button1.Name = "button1";
            this.button1.UseUnderline = true;
            this.button1.Relief = ((Gtk.ReliefStyle)(2));
            // Container child button1.Gtk.Container+ContainerChild
            Gtk.Alignment w4 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w5 = new Gtk.HBox();
            w5.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w6 = new Gtk.Image();
            w6.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-execute", Gtk.IconSize.Menu, 16);
            w5.Add(w6);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w8 = new Gtk.Label();
            w8.LabelProp = Mono.Unix.Catalog.GetString("_Invoke");
            w8.UseUnderline = true;
            w5.Add(w8);
            w4.Add(w5);
            this.button1.Add(w4);
            this.vbox.Add(this.button1);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox[this.button1]));
            w12.Position = 3;
            w12.Expand = false;
            w12.Fill = false;
            this.Add(this.vbox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
