// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.Upnp.GtkClient {
    
    
    public partial class MainWindow {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.VBox vbox1;
        
        private Gtk.HPaned hpaned;
        
        private Gtk.ScrolledWindow GtkScrolledWindow;
        
        private Gtk.TreeView list;
        
        private Gtk.VBox infoBox;
        
        private Gtk.Label infoFiller;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Mono.Upnp.GtkClient.MainWindow
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.WidthRequest = 0;
            this.HeightRequest = 0;
            this.Name = "Mono.Upnp.GtkClient.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("Mono.Upnp");
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            // Container child Mono.Upnp.GtkClient.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hpaned = new Gtk.HPaned();
            this.hpaned.CanFocus = true;
            this.hpaned.Name = "hpaned";
            this.hpaned.Position = 283;
            this.hpaned.BorderWidth = ((uint)(5));
            // Container child hpaned.Gtk.Paned+PanedChild
            this.GtkScrolledWindow = new Gtk.ScrolledWindow();
            this.GtkScrolledWindow.Name = "GtkScrolledWindow";
            this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
            // Container child GtkScrolledWindow.Gtk.Container+ContainerChild
            this.list = new Gtk.TreeView();
            this.list.CanFocus = true;
            this.list.Name = "list";
            this.GtkScrolledWindow.Add(this.list);
            this.hpaned.Add(this.GtkScrolledWindow);
            Gtk.Paned.PanedChild w3 = ((Gtk.Paned.PanedChild)(this.hpaned[this.GtkScrolledWindow]));
            w3.Resize = false;
            // Container child hpaned.Gtk.Paned+PanedChild
            this.infoBox = new Gtk.VBox();
            this.infoBox.Name = "infoBox";
            this.infoBox.Spacing = 6;
            // Container child infoBox.Gtk.Box+BoxChild
            this.infoFiller = new Gtk.Label();
            this.infoFiller.Name = "infoFiller";
            this.infoFiller.LabelProp = Mono.Unix.Catalog.GetString("Select a device or service");
            this.infoBox.Add(this.infoFiller);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.infoBox[this.infoFiller]));
            w4.Position = 0;
            w4.Fill = false;
            this.hpaned.Add(this.infoBox);
            this.vbox1.Add(this.hpaned);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox1[this.hpaned]));
            w6.Position = 0;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 786;
            this.DefaultHeight = 487;
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
        }
    }
}
