// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.Upnp.GtkClient {
    
    
    public partial class DeviceDescriptionInfo {
        
        private Gtk.Table table1;
        
        private Gtk.Label deviceType;
        
        private Gtk.Label friendlyName;
        
        private Gtk.VBox iconBox;
        
        private Gtk.Label label1;
        
        private Gtk.Label label10;
        
        private Gtk.Label label11;
        
        private Gtk.Label label2;
        
        private Gtk.Label label3;
        
        private Gtk.Label label4;
        
        private Gtk.Label label5;
        
        private Gtk.Label label6;
        
        private Gtk.Label label7;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.Label manufacturer;
        
        private Gtk.Label manufacturerUrl;
        
        private Gtk.Label modelName;
        
        private Gtk.Label modelNumber;
        
        private Gtk.Label modelUrl;
        
        private Gtk.Label serialNumber;
        
        private Gtk.Label udn;
        
        private Gtk.Label upc;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Mono.Upnp.GtkClient.DeviceDescriptionInfo
            Stetic.BinContainer.Attach(this);
            this.Name = "Mono.Upnp.GtkClient.DeviceDescriptionInfo";
            // Container child Mono.Upnp.GtkClient.DeviceDescriptionInfo.Gtk.Container+ContainerChild
            this.table1 = new Gtk.Table(((uint)(11)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(10));
            this.table1.ColumnSpacing = ((uint)(10));
            this.table1.BorderWidth = ((uint)(10));
            // Container child table1.Gtk.Table+TableChild
            this.deviceType = new Gtk.Label();
            this.deviceType.Name = "deviceType";
            this.deviceType.Xalign = 0F;
            this.deviceType.LabelProp = "deviceType";
            this.deviceType.Selectable = true;
            this.table1.Add(this.deviceType);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.deviceType]));
            w1.LeftAttach = ((uint)(1));
            w1.RightAttach = ((uint)(2));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.friendlyName = new Gtk.Label();
            this.friendlyName.Name = "friendlyName";
            this.friendlyName.Xalign = 0F;
            this.friendlyName.LabelProp = "friendlyName";
            this.friendlyName.Selectable = true;
            this.table1.Add(this.friendlyName);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.friendlyName]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.iconBox = new Gtk.VBox();
            this.iconBox.Name = "iconBox";
            this.iconBox.Spacing = 6;
            this.table1.Add(this.iconBox);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.iconBox]));
            w3.TopAttach = ((uint)(10));
            w3.BottomAttach = ((uint)(11));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.Xalign = 1F;
            this.label1.Yalign = 0F;
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("<b>Icons</b>");
            this.label1.UseMarkup = true;
            this.table1.Add(this.label1);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.label1]));
            w4.TopAttach = ((uint)(10));
            w4.BottomAttach = ((uint)(11));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.Xalign = 1F;
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("<b>UPC</b>");
            this.label10.UseMarkup = true;
            this.table1.Add(this.label10);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label10]));
            w5.TopAttach = ((uint)(9));
            w5.BottomAttach = ((uint)(10));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.Xalign = 1F;
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("<b>Device Type</b>");
            this.label11.UseMarkup = true;
            this.table1.Add(this.label11);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.label11]));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 1F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("<b>UDN</b>");
            this.label2.UseMarkup = true;
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label3 = new Gtk.Label();
            this.label3.Name = "label3";
            this.label3.Xalign = 1F;
            this.label3.LabelProp = Mono.Unix.Catalog.GetString("<b>Friendly Name</b>");
            this.label3.UseMarkup = true;
            this.table1.Add(this.label3);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.label3]));
            w8.TopAttach = ((uint)(2));
            w8.BottomAttach = ((uint)(3));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label4 = new Gtk.Label();
            this.label4.Name = "label4";
            this.label4.Xalign = 1F;
            this.label4.LabelProp = Mono.Unix.Catalog.GetString("<b>Manufacturer</b>");
            this.label4.UseMarkup = true;
            this.table1.Add(this.label4);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.label4]));
            w9.TopAttach = ((uint)(3));
            w9.BottomAttach = ((uint)(4));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.Xalign = 1F;
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("<b>Manufacturer URL</b>");
            this.label5.UseMarkup = true;
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w10.TopAttach = ((uint)(4));
            w10.BottomAttach = ((uint)(5));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.Xalign = 1F;
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("<b>Model Name</b>");
            this.label6.UseMarkup = true;
            this.table1.Add(this.label6);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table1[this.label6]));
            w11.TopAttach = ((uint)(5));
            w11.BottomAttach = ((uint)(6));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.Xalign = 1F;
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("<b>Model Number</b>");
            this.label7.UseMarkup = true;
            this.table1.Add(this.label7);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.table1[this.label7]));
            w12.TopAttach = ((uint)(6));
            w12.BottomAttach = ((uint)(7));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.Xalign = 1F;
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("<b>Model URL</b>");
            this.label8.UseMarkup = true;
            this.table1.Add(this.label8);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
            w13.TopAttach = ((uint)(7));
            w13.BottomAttach = ((uint)(8));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.Xalign = 1F;
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("<b>Serial Number</b>");
            this.label9.UseMarkup = true;
            this.table1.Add(this.label9);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.table1[this.label9]));
            w14.TopAttach = ((uint)(8));
            w14.BottomAttach = ((uint)(9));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.manufacturer = new Gtk.Label();
            this.manufacturer.Name = "manufacturer";
            this.manufacturer.Xalign = 0F;
            this.manufacturer.LabelProp = "manufacturer";
            this.manufacturer.Selectable = true;
            this.table1.Add(this.manufacturer);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.table1[this.manufacturer]));
            w15.TopAttach = ((uint)(3));
            w15.BottomAttach = ((uint)(4));
            w15.LeftAttach = ((uint)(1));
            w15.RightAttach = ((uint)(2));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.manufacturerUrl = new Gtk.Label();
            this.manufacturerUrl.Name = "manufacturerUrl";
            this.manufacturerUrl.Xalign = 0F;
            this.manufacturerUrl.LabelProp = "manufacturerUrl";
            this.manufacturerUrl.Selectable = true;
            this.table1.Add(this.manufacturerUrl);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.manufacturerUrl]));
            w16.TopAttach = ((uint)(4));
            w16.BottomAttach = ((uint)(5));
            w16.LeftAttach = ((uint)(1));
            w16.RightAttach = ((uint)(2));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.modelName = new Gtk.Label();
            this.modelName.Name = "modelName";
            this.modelName.Xalign = 0F;
            this.modelName.LabelProp = "modelUrl";
            this.modelName.Selectable = true;
            this.table1.Add(this.modelName);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table1[this.modelName]));
            w17.TopAttach = ((uint)(5));
            w17.BottomAttach = ((uint)(6));
            w17.LeftAttach = ((uint)(1));
            w17.RightAttach = ((uint)(2));
            w17.XOptions = ((Gtk.AttachOptions)(4));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.modelNumber = new Gtk.Label();
            this.modelNumber.Name = "modelNumber";
            this.modelNumber.Xalign = 0F;
            this.modelNumber.LabelProp = "modelNumber";
            this.modelNumber.Selectable = true;
            this.table1.Add(this.modelNumber);
            Gtk.Table.TableChild w18 = ((Gtk.Table.TableChild)(this.table1[this.modelNumber]));
            w18.TopAttach = ((uint)(6));
            w18.BottomAttach = ((uint)(7));
            w18.LeftAttach = ((uint)(1));
            w18.RightAttach = ((uint)(2));
            w18.XOptions = ((Gtk.AttachOptions)(4));
            w18.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.modelUrl = new Gtk.Label();
            this.modelUrl.Name = "modelUrl";
            this.modelUrl.Xalign = 0F;
            this.modelUrl.LabelProp = "modelUrl";
            this.modelUrl.Selectable = true;
            this.table1.Add(this.modelUrl);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table1[this.modelUrl]));
            w19.TopAttach = ((uint)(7));
            w19.BottomAttach = ((uint)(8));
            w19.LeftAttach = ((uint)(1));
            w19.RightAttach = ((uint)(2));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.serialNumber = new Gtk.Label();
            this.serialNumber.Name = "serialNumber";
            this.serialNumber.Xalign = 0F;
            this.serialNumber.LabelProp = "serialNumber";
            this.serialNumber.Selectable = true;
            this.table1.Add(this.serialNumber);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table1[this.serialNumber]));
            w20.TopAttach = ((uint)(8));
            w20.BottomAttach = ((uint)(9));
            w20.LeftAttach = ((uint)(1));
            w20.RightAttach = ((uint)(2));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.udn = new Gtk.Label();
            this.udn.Name = "udn";
            this.udn.Xalign = 0F;
            this.udn.LabelProp = "udn";
            this.udn.Selectable = true;
            this.table1.Add(this.udn);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table1[this.udn]));
            w21.TopAttach = ((uint)(1));
            w21.BottomAttach = ((uint)(2));
            w21.LeftAttach = ((uint)(1));
            w21.RightAttach = ((uint)(2));
            w21.XOptions = ((Gtk.AttachOptions)(4));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.upc = new Gtk.Label();
            this.upc.Name = "upc";
            this.upc.Xalign = 0F;
            this.upc.LabelProp = "upc";
            this.upc.Selectable = true;
            this.table1.Add(this.upc);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table1[this.upc]));
            w22.TopAttach = ((uint)(9));
            w22.BottomAttach = ((uint)(10));
            w22.LeftAttach = ((uint)(1));
            w22.RightAttach = ((uint)(2));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            this.Add(this.table1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
        }
    }
}
