// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Mono.Upnp.GtkClient {
    
    
    public partial class ActionInvocationWindow {
        
        private Gtk.VBox vbox;
        
        private Gtk.Label name;
        
        private Gtk.VBox inputsBox;
        
        private Gtk.Button invoke;
        
        private Gtk.VBox outputsBox;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Mono.Upnp.GtkClient.ActionInvocationWindow
            this.WidthRequest = 0;
            this.HeightRequest = 0;
            this.Name = "Mono.Upnp.GtkClient.ActionInvocationWindow";
            this.Title = "Invoke Action";
            this.WindowPosition = ((Gtk.WindowPosition)(1));
            this.DefaultWidth = 0;
            this.DefaultHeight = 0;
            // Container child Mono.Upnp.GtkClient.ActionInvocationWindow.Gtk.Container+ContainerChild
            this.vbox = new Gtk.VBox();
            this.vbox.Name = "vbox";
            this.vbox.Spacing = 6;
            this.vbox.BorderWidth = ((uint)(6));
            // Container child vbox.Gtk.Box+BoxChild
            this.name = new Gtk.Label();
            this.name.Name = "name";
            this.name.Xalign = 0F;
            this.name.LabelProp = "<big><b>action</b></big>";
            this.name.UseMarkup = true;
            this.vbox.Add(this.name);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox[this.name]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox.Gtk.Box+BoxChild
            this.inputsBox = new Gtk.VBox();
            this.inputsBox.Name = "inputsBox";
            this.inputsBox.Spacing = 6;
            this.vbox.Add(this.inputsBox);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox[this.inputsBox]));
            w2.Position = 1;
            // Container child vbox.Gtk.Box+BoxChild
            this.invoke = new Gtk.Button();
            this.invoke.CanFocus = true;
            this.invoke.Name = "invoke";
            this.invoke.UseUnderline = true;
            this.invoke.Relief = ((Gtk.ReliefStyle)(2));
            // Container child invoke.Gtk.Container+ContainerChild
            Gtk.Alignment w3 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w4 = new Gtk.HBox();
            w4.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w5 = new Gtk.Image();
            w5.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-execute", Gtk.IconSize.Menu, 16);
            w4.Add(w5);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w7 = new Gtk.Label();
            w7.LabelProp = Mono.Unix.Catalog.GetString("_Invoke");
            w7.UseUnderline = true;
            w4.Add(w7);
            w3.Add(w4);
            this.invoke.Add(w3);
            this.vbox.Add(this.invoke);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.vbox[this.invoke]));
            w11.Position = 2;
            w11.Expand = false;
            w11.Fill = false;
            // Container child vbox.Gtk.Box+BoxChild
            this.outputsBox = new Gtk.VBox();
            this.outputsBox.Name = "outputsBox";
            this.outputsBox.Spacing = 6;
            this.vbox.Add(this.outputsBox);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox[this.outputsBox]));
            w12.Position = 3;
            this.Add(this.vbox);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.invoke.Clicked += new System.EventHandler(this.OnInvokeClicked);
        }
    }
}
